---
services:
    Developtech_agility.project_manager:
        class: Developtech\AgilityBundle\Manager\ProjectManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%Developtech_agility.model.project.class%"
