<?php

namespace Developtech\AgilityBundle\Repository;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
