<?php

namespace Developtech\AgilityBundle\Repository;

use Developtech\AgilityBundle\Model\ProjectModel;

use Developtech\AgilityBundle\Entity\Job;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ProjectModel $project
     * @param integer $status
     * @return integer
     */
    public function countPerStatus(ProjectModel $project, $status) {
        $statement = $this->getEntityManager()->getConnection()->prepare(
            "SELECT COUNT(*) as nb_feedbacks FROM {$this->getEntityManager()->getClassMetadata(Job::class)->getTableName()} " .
            "WHERE project_id = :project_id AND status = :status AND type = '" . Job::TYPE_FEEDBACK . "'"
        );
        $statement->execute([
            'project_id' => $project->getId(),
            'status' => $status
        ]);
        return (int) $statement->fetch()['nb_feedbacks'];
    }
}
